### ISSUE TITLE
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by cluc-md** [faster-than-light/ftl#8]
I heard about you from TalkPythonToMe - this looks awesome! I am trying to use the cli, was hoping to add this to our CI setup. I installed with pip, but when I try running `ftl --project "Master" --sid MyRealSidFromWebApp push *` I get the following output:

 Traceback (most recent call last):
  File "/usr/local/bin/ftl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bugcatcher/ftl.py", line 721, in main
    commands\[args.command](args)
  File "/usr/local/lib/python3.7/site-packages/bugcatcher/ftl.py", line 396, in cmd_push
    res, data, err, errstr = rest_call(args, 'GET', "/project/%s" % args.project)
  File "/usr/local/lib/python3.7/site-packages/bugcatcher/ftl.py", line 293, in rest_call
    dict_res = res.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I'm going to go ahead and try uploading from the web app, but I'm not sure what I did wrong here. I have quite a bit of python experience and I can't remember the last time I had any trouble running a package from pip out of the box.

**Comment by retzion** [comment]
Oops, @cluc-md, I had not been using the default API endpoint recently.
It was pointed at the web app. It should work now. 2aa59efb5fa03da0873ef05b553a7f57adad0240

Thanks for the report!
